### ISSUE TITLE
$localStorage.key = undefined; assignment is not persistent. 

### ISSUE THREAD

**Issue by dnozay** [gsklee/ngStorage#83] opened 2015-04-27 23:28 UTC
```
$localStorage.key = { a: 1 };
// some other stuff
$localStorage.key = undefined;
```
when I reload, I always get back the object rather than `undefined`.

**Comment by figalex** [comment] 2015-04-30 22:54
Same issue here

**Comment by dudeitscesar** [comment] 2015-05-05 20:19
It's possible that the persistent issues are related to Android's WebView, if you are on Android. [See here](https://code.google.com/p/chromium/issues/detail?id=479767) for some additional details, as this seems to be an issue with the WebView and not necessarily this plugin. It also seems to be fixed on the latest version that is being rolled out soon (as of 5/5/2015).

**Comment by dnozay** [comment] 2015-05-06 00:12
I think it is an edge case with the checks within the block guarded by [`angular.equals($storage, _last$storage)`](https://github.com/gsklee/ngStorage/blob/master/ngStorage.js#L73). I'm on OSX so definitely not a WebView issue.

**Comment by egilkh** [comment] 2015-08-18 13:53
Hoy!

It seems the problem is caused by `angular.isDefined` which will return false for `undefined` and thus not call `.setItem` on the storage. So it never gets written down to the webStorage. 

According to the docs from way back https://github.com/gsklee/ngStorage#permitted-values--demo undefined should in fact be removed like functions.

This tied with the fact that isDefined is not used for the delete in temp$storage means they get removed from the list of items that will be removed. If it did get removed it would be undefined on next check.

I've added a wip commit if anyone wants to test / comment at https://github.com/egilkh/ngStorage/commit/a1af938aebd93ccfcf18235d8180323c65a5c8d9

**Closed** 2015-08-19 17:43 UTC
